global:
  scrape_interval: 5s

scrape_configs:
  - job_name: "otel-collector"
    static_configs:
      - targets: ["otelcol:9464"]  # collectorâ€™s Prometheus endpoint
      #host.docker.internal:9090